### ISSUE TITLE
Incorrect results for `constraint` on directed graphs

### ISSUE THREAD

**Issue by jsfalk** [rcc-uchicago/influenceR#6]
The `influenceR` and `igraph` implementations of `constraint` give different results for directed graphs. Here is a minimal working example showing the difference:

```R
graph_df <- data.frame(from=c(1, 1, 1, 2), to=c(2, 3, 4, 3))
g <- graph_from_data_frame(graph_df, directed=TRUE)
all.equal(influenceR::constraint(g), igraph::constraint(g))
```

My understanding is that even for directed graphs, all connections should be considered (in-in, out-out, in-out, and out-out), but it appears that `influenceR` only considers one direction. I'm not sure the best way to fix this. Also, `networkX` gives `nan` for the constraint values for nodes 3 and 4, whereas `igraph` gives them defined values, so I'm not confident enough in the desired behavior to make a PR without further discussion.

**Comment by khanna7** [comment]
Thank you @jsfalk. `influenceR` so far only handles undirected graphs.
