### ISSUE TITLE
Orphaned package on CRAN

### ISSUE THREAD

**Issue by DDorch** [rcc-uchicago/influenceR#8]
The package is noted as orphaned on the CRAN for 4 days: https://cran.r-project.org/package=influenceR

DiagrammeR is the only package importing influenceR and all the packages depending on it are impacted by warnings on R CMD CHECK (See https://github.com/rich-iannone/DiagrammeR/issues/485).

Is there still a maintainer for this package and can he/she contact the CRAN?

**Comment by khanna7** [comment]
Hello,

Thank you for your message. I am the maintainer. How can I help you?

Aditya

**Comment by DDorch** [comment]
I think you should send an email to cran-sysadmin@R-project.org and explain that you are still the maintainer of the package.

Maybe they have classified the package as orphaned because your e-mail has changed?

**Comment by khanna7** [comment]
@DDorch: Hello - The package is now updated on CRAN:
https://cran.r-project.org/web/packages/influenceR/index.html. Note the
updated link for the dev version on GitHub. It should compile correctly now.
